### ISSUE TITLE
PARSER error: enum tag redefined

### ISSUE THREAD

**Issue by darmie** [xlab/c-for-go#102]
I am getting an error with parsing enums

```
$ go-kinc % c-for-go -ccincl -ccdefs kinc.yml
  processing kinc.yml ⠋[WARN] `cpp -dM` failed: exit status 1
  processing kinc.yml ⠸Sources/kinc/image.h:11:14: enum tag redefined, previous definition: Sources/kinc/image.h:11:9
Sources/kinc/image.h:18:14: enum tag redefined, previous definition: Sources/kinc/image.h:18:9
Sources/kinc/image.h:11:14: enum tag redefined, previous definition: Sources/kinc/image.h:11:9
Sources/kinc/image.h:18:14: enum tag redefined, previous definition: Sources/kinc/image.h:18:9
Sources/kinc/image.h:11:14: enum tag redefined, previous definition: Sources/kinc/image.h:11:9
Sources/kinc/image.h:18:14: enum tag redefined, previous definition: Sources/kinc/image.h:18:9
Sources/kinc/image.h:11:14: enum tag redefined, previous definition: Sources/kinc/image.h:11:9
Sources/kinc/image.h:18:14: enum tag redefined, previous definition: Sources/kinc/image.h:18:9
Sources/kinc/image.h:11:14: enum tag redefined, previous definition: Sources/kinc/image.h:11:9
Sources/kinc/image.h:18:14: enum tag redefined, previous definition: Sources/kinc/image.h:18:9
too many errors
```
image.h
```c
#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum kinc_image_compression {
	KINC_IMAGE_COMPRESSION_NONE,
	KINC_IMAGE_COMPRESSION_DXT5,
	KINC_IMAGE_COMPRESSION_ASTC,
	KINC_IMAGE_COMPRESSION_PVRTC
} kinc_image_compression_t;

typedef enum kinc_image_format {
	KINC_IMAGE_FORMAT_RGBA32,
	KINC_IMAGE_FORMAT_GREY8,
	KINC_IMAGE_FORMAT_RGB24,
	KINC_IMAGE_FORMAT_RGBA128,
	KINC_IMAGE_FORMAT_RGBA64,
	KINC_IMAGE_FORMAT_A32,
	KINC_IMAGE_FORMAT_BGRA32,
	KINC_IMAGE_FORMAT_A16
} kinc_image_format_t;

typedef struct kinc_image {
	int width, height, depth;
	kinc_image_format_t format;
	unsigned internal_format;
	kinc_image_compression_t compression;
	void *data;
	int data_size;
} kinc_image_t;

size_t kinc_image_init(kinc_image_t *image, void *memory, int width, int height, kinc_image_format_t format);
size_t kinc_image_init3d(kinc_image_t *image, void *memory, int width, int height, int depth, kinc_image_format_t format);
size_t kinc_image_init_from_file(kinc_image_t *image, void *memory, const char *filename);
void kinc_image_init_from_bytes(kinc_image_t *image, void *data, int width, int height, kinc_image_format_t format);
void kinc_image_init_from_bytes3d(kinc_image_t *image, void *data, int width, int height, int depth, kinc_image_format_t format);
void kinc_image_destroy(kinc_image_t *image);
int kinc_image_at(kinc_image_t *image, int x, int y);
uint8_t *kinc_image_get_pixels(kinc_image_t *image);

int kinc_image_format_sizeof(kinc_image_format_t format);

#ifdef __cplusplus
}
#endif
```
config
```yaml
PARSER:
  IncludePaths: ["/usr/include", "/usr/local/include", "/usr/local/cellar", "Sources", "Backends/Graphics4/OpenGL/Sources","Backends/Graphics5/G5onG4/Sources", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include"]
  SourcesPaths: ["kinc/window.h", "kinc/display.h", "kinc/color.h", "kinc/image.h", "kinc/system.h", "kinc/graphics4/graphics.h", "kinc/graphics5/graphics.h", "kinc/graphics1/graphics.h", "kinc/math/matrix.h", "kinc/math/random.h", "kinc/math/vector.h"]
  Defines: 
    KINC_FUNC: {}
TRANSLATOR: 
  ConstCharIsString: true
  ConstUCharIsString: false
  ConstRules: 
    defines: expand
    enum: eval
  Rules: 
    global: 
      - {transform: lower}
      - {action: accept, from: "^kinc_"}
```
