### ISSUE TITLE
Request: v8

### ISSUE THREAD

**Issue by tmc** [xlab/c-for-go#104]
My naive attempt of generating bindings for v8.h via:

```yaml
GENERATOR: 
  PackageName: v8
  PackageDescription: "Package v8 provides Go bindings for V8"
  # PkgConfigOpts: [v8]
  Includes: ["v8.h"]
  Options:
    SafeStrings: true
PARSER: 
  IncludePaths: [
    "/usr/include",
    "/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/usr/include/",
    "../../v8/v8/include",
  ]
  SourcesPaths: ["v8.h"]
```

results in:
```
  processing v8.yml ⠙[ERR] ../../v8/v8/include/cppgc/common.h:11:11: unexpected identifier cppgc, expected one of ['(', ')', ',', ':', ';', '=', '[', '{', _Bool, _Complex, _Noreturn, _Static_assert, asm, auto, char, const, double, enum, extern, float, inline, int, long, register, restrict, short, signed, static, struct, typedef, typedefname, typeof, union, unsigned, void, volatile] (and 7 more errors)
```
