### ISSUE TITLE
file not found: stdbool.h

### ISSUE THREAD

**Issue by blacktop** [xlab/c-for-go#114]
REPO - https://github.com/blacktop/arm64-cgo

`disassembler.yml`
```yaml
---
GENERATOR:
  PackageName: arm64
  PackageDescription: "Package arm64 provides Go bindings for then Binary Ninja Arm64 Disassembler"
  PackageLicense: "THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS."
  Includes: ["decode.h", "format.h"]

PARSER:
  Defines:
    _POSIX_C_SOURCE: 1
  IncludePaths: [
    "/usr/include",
    "/usr/local/include",
    "/usr/local/Cellar/gcc/11.1.0_1/include",
    "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include",
  ]
  SourcesPaths: ["disassembler/decode.h", "disassembler/format.h"]
 ``` 

```bash
❯ xcode-select --install                          
xcode-select: error: command line tools are already installed, use "Software Update" to install updates

❯ xcode-select -p                                      
/Applications/XCode.app/Contents/Developer
```

Just going into the dir and running `make -f Makefile-local` works

### ERROR 

Running `c-for-go -ccdefs disassembler.yml`

```bash
❯ make
c-for-go -ccdefs disassembler.yml
  processing disassembler.yml ⠹[ERR] disassembler/decode.h:3:10: include file not found: stdbool.h. Search paths:
        /usr/include
        /usr/local/include
        /usr/local/Cellar/gcc/11.1.0_1/include
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
        /Users/blacktop/Projects/GitHub/blacktop/arm64-cgo
        /usr/include
        /usr/local/include
        /usr/local/Cellar/gcc/11.1.0_1/include
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
        /Users/blacktop/Projects/GitHub/blacktop/arm64-cgo (and 3 more errors)
make: *** [all] Error 1
```

**Comment by blacktop** [comment]
Code seems VERY self-contained. I'm sure I'm doing something dumb

**Comment by blacktop** [comment]
Updated `disassembler.yml` 
```yaml
---
GENERATOR:
  PackageName: arm64
  PackageDescription: "Package arm64 provides Go bindings for then Binary Ninja Arm64 Disassembler"
  PackageLicense: "THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS."
  Includes: ["decode.h", "format.h"]

PARSER:
  IncludePaths: [
    "/usr/include",
    "/usr/local/include",
    "/usr/local/Cellar/gcc/11.1.0_1/include",
    "/usr/local/Cellar/gcc/11.1.0_1/lib/gcc/11/gcc/x86_64-apple-darwin20/11.1.0/include",
    "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include",
  ]
  SourcesPaths: ["disassembler/decode.h", "disassembler/format.h"]
```

### NEW ERRORS

```bash
❯ make      
c-for-go -ccdefs disassembler.yml
  processing disassembler.yml ⠹disassembler/operations.h:4:6: enum tag redefined, previous definition: disassembler/operations.h:4:1
disassembler/encodings_dec.h:8:6: enum tag redefined, previous definition: disassembler/encodings_dec.h:8:1
disassembler/regs.h:13:6: enum tag redefined, previous definition: disassembler/regs.h:13:1
disassembler/sysregs.h:3:6: enum tag redefined, previous definition: disassembler/sysregs.h:3:1
disassembler/decode.h:23:6: enum tag redefined, previous definition: disassembler/decode.h:23:1
disassembler/decode.h:396:6: enum tag redefined, previous definition: disassembler/decode.h:396:1
disassembler/decode.h:416:6: enum tag redefined, previous definition: disassembler/decode.h:416:1
disassembler/decode.h:424:6: enum tag redefined, previous definition: disassembler/decode.h:424:1
disassembler/decode.h:431:6: enum tag redefined, previous definition: disassembler/decode.h:431:1
disassembler/encodings_dec.h:8:6: enum tag redefined, previous definition: disassembler/encodings_dec.h:8:1
too many errors
make: *** [all] Error 1
```
