### ISSUE TITLE
How to add a Framework?

### ISSUE THREAD

**Issue by danjenkins** [xlab/c-for-go#129]
I've offered up CFLAGS and LDFLAGS for how to find the `CoreFoundation` framework but while it's processing the file given in `Includes` in the `GENERATOR` section...it fails to find the framework during the `processing` step

```
processing decklink.yml ⠋[ERR] ./sdk/Mac/include/DeckLinkAPI.h:46:10: include file not found: CoreFoundation/CoreFoundation.h. Search paths:
```

The search paths don't note the flags....

Here are the flags given...

```
  FlagGroups:
    - name: CFLAGS
      traits: ["darwin"]
      flags:
        - "-F/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/System/Library/Frameworks"
        - "-framework CoreFoundation"
    - name: LDFLAGS
      traits: ["darwin"]
      flags:
        - "-F/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/System/Library/Frameworks"
        - "-framework CoreFoundation"
```

If anyones got any ideas that would be great :D
