### ISSUE TITLE
With the latest commit (c95ebd03aba931e7248a6011f86d822ab878d00c), c-for-go can no longer generate defines

### ISSUE THREAD

**Issue by yeahdongcn** [xlab/c-for-go#132]
I'm using the following configurations to generate consts, but after I switch to the latest commit of c-for-go, `#define XYZ_ABC 10` can no longer generate the following go code:

```golang
const (
	ABC = 10
}
```

Please find my config file below:

```yaml
TRANSLATOR:
  ConstRules:
    defines: eval
    enum: eval
  Rules:
    const:
      - {action: accept, from: "^XYZ_"}
      - {action: replace, from: "^XYZ_"}
      - {action: replace, from: "_t$"}
      - {transform: export}
```

While reverting to the previous commit, everything works fine.
