### ISSUE TITLE
unexpected string literal "C"

### ISSUE THREAD

**Issue by 5k3105** [xlab/c-for-go#14]
I have what I thought was very simple C file. I get: ```unexpected string literal "C"```

```  processing dexapi.yml ⠋[ERR] DexApi.h:28:8: unexpected string literal "C", expected one of ['(', ')', '*', ',', ';', '[', _Bool, _Complex, _Noreturn, auto, char, const, double, enum, extern, float, identifier, inline, int, long, register, restrict, short, signed, static, struct, typedef, typedefname, typeof, union, unsigned, void, volatile]```

yml file is:

```yml
--- 
GENERATOR: 
  PackageName: dexapi
  PackageDescription: "Package dexapi provides Go bindings for Dex Tools 2.23 for IWR3 decode to DF3"
  PackageLicense: "THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS."
  Includes: ["DexApi.h"]
  
PARSER: 
  SourcesPaths: ["DexApi.h"]
```

h file is:

```c++
// -*- C++ -*-
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ 
#if !defined DexApi_h
#    define DexApi_h

typedef enum { eStopped=0, eTransition=1, eRunning=2 }STATES_E;
 
typedef enum { no_error  = 0,
               not_ready = -1,
               no_data   = -2,
               no_toc    = -3
} ERRORS_E;

enum {
   eMAX_API_VERSION=40  
};

#define DEX_EXP __declspec(dllexport)
#define DEX_IMP __declspec(dllimport)

#define API_SOURCE 1            // 1 for DLL; 0 for application
#if API_SOURCE==1
#define  DEX_API DEX_EXP
#else
#define  DEX_API DEX_IMP
#endif

extern "C" {
// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
void DEX_API set_work_dir( const char *pName);

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
void DEX_API set_batch_mode( int mode);
  
// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
void DEX_API set_bin_filename( const char *pName);

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
void DEX_API set_project_name(const char *pName);

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
void DEX_API get_dll_version(char *pName, int size);

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
int DEX_API get_run_state();

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
int DEX_API get_delayed_result();

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
int DEX_API get_frame_count();

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
int DEX_EXP get_shot_rate();

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
int DEX_API get_1pps_count();

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
int DEX_API get_strip_count();

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
int DEX_API copy_ssd();

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
int DEX_API make_strips();

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
int DEX_API make_strip( int choice);

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
int DEX_API get_section_pkts(int first, int last);

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
int DEX_API list_forward();

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
int DEX_API make_df3();

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
int DEX_API list_phy_toc();

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
void DEX_API get_phy_info( int *pArray, int num_ints );

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
void DEX_EXP get_reader_progress( int *pArray, int num_ints );
}

#endif // DexApi.h
```

BTW, I did post the working version you helped me with last month here:
https://github.com/5k3105/nidaq

It has been working great.

**Comment by cznic** [comment]
This seems like a C++ only header file to me. The `extern "C" {` should be, for C compatibility, wrapped in

```c
#ifdef __cplusplus
extern "C" {
#endif
```

See also: [Combining C++ and C - how does #ifdef __cplusplus work?](http://stackoverflow.com/q/3789340)

**Comment by 5k3105** [comment]
That worked. Now I have:

``` processing dexapi.yml ⠋[ERR] DexApi.h:32:14: unexpected identifier set_work_dir```

**Comment by 5k3105** [comment]
Moved ```#ifdef __cplusplus``` to top of file and endif to bottom. Compiled.

**Comment by xlab** [comment]
@5k3105 oh dude you should really check out how C defines work in general,
also the link [Combining C++ and C - how does #ifdef __cplusplus work?](http://stackoverflow.com/q/3789340) also tells how to do this properly.

**Comment by xlab** [comment]
@5k3105 Also, everything is ignored by default, you should include functions and other types you want to use explicitly. Remember `nidaqmx.yml`? 

```yaml
  Rules: 
    global:   
      - {action: accept, from: "^DAQmx"}
      - {action: replace, from: "^DAQmx"}
      - {transform: export}
    post-global: 
      - {action: replace, from: _$}
      - {load: snakecase}
```

In this case you can't use prefixes, there is no prefixes, so specify exact function names and const definitions. E.g.

```
- {action: accept, from: "^make_strips$"}
- {action: accept, from: "^ list_forward$"}
- {action: accept, from: "^ list_phy_toc$"}
...
```

**Comment by 5k3105** [comment]
Sorry and thanks for the help.

Error:
```
  processing dexapi.yml ⠋[ERR] DexApi.h:37:14: unexpected identifier set_work_dir, expected one of ['(', ')', ',', ':', ';', '=', '[', '{', _Bool, _Complex, _Noreturn, _Static_assert, asm, auto, char, const, double, enum, extern, float, inline, int, long, register, restrict, short, signed, static, struct, typedef, typedefname, typeof, union, unsigned, void, volatile]
```

header:

```c++
// -*- C++ -*-
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ 

//#define __cplusplus


#if !defined DexApi_h
#    define DexApi_h

typedef enum { eStopped=0, eTransition=1, eRunning=2 }STATES_E;
 
typedef enum { no_error  = 0,
               not_ready = -1,
               no_data   = -2,
               no_toc    = -3
} ERRORS_E;

enum {
   eMAX_API_VERSION=40  
};

#define DEX_EXP __declspec(dllexport)
#define DEX_IMP __declspec(dllimport)

#define API_SOURCE 1            // 1 for DLL; 0 for application
#if API_SOURCE==1
#define  DEX_API DEX_EXP
#else
#define  DEX_API DEX_IMP
#endif

#ifdef __cplusplus
extern "C" {
#endif
// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
void DEX_API set_work_dir( const char *pName);

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
void DEX_API set_batch_mode( int mode);
  
// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
void DEX_API set_bin_filename( const char *pName);

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
void DEX_API set_project_name(const char *pName);

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
void DEX_API get_dll_version(char *pName, int size);

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
int DEX_API get_run_state();

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
int DEX_API get_delayed_result();

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
int DEX_API get_frame_count();

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
int DEX_EXP get_shot_rate();

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
int DEX_API get_1pps_count();

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
int DEX_API get_strip_count();

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
int DEX_API copy_ssd();

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
int DEX_API make_strips();

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
int DEX_API make_strip( int choice);

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
int DEX_API get_section_pkts(int first, int last);

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
int DEX_API list_forward();

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
int DEX_API make_df3();

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
int DEX_API list_phy_toc();

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
void DEX_API get_phy_info( int *pArray, int num_ints );

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
void DEX_EXP get_reader_progress( int *pArray, int num_ints );

#ifdef __cplusplus
}
#endif

#endif // DexApi.h

```

yaml:

```yaml
--- 
GENERATOR: 
  PackageName: dexapi
  PackageDescription: "Package dexapi provides Go bindings for Dex Tools 2.23 for IWR3 decode to DF3"
  PackageLicense: "THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS."
  Includes: ["DexApi.h"]

  Defines:
    DexApi_h: 1
    
PARSER: 
  SourcesPaths: ["DexApi.h"]

  Rules: 
    global:
      - {action: accept, from: "^set_work_dir$"}
      - {action: accept, from: "^make_strips$"}
      - {action: accept, from: "^list_forward$"}
      - {action: accept, from: "^list_phy_toc$"}
    
    


```

**Comment by 5k3105** [comment]
Hi,

H file same as above.

Working on this again. Error was:

```unexpected identifier set_work_dir, expected one of ['(', ')', ',', ':',``` etc...

Changing
```c
void DEX_API set_work_dir( const char *pName);
```
to (removing DEX_API)
```c
void set_work_dir(const char *pName);
```

allows it to compile without error, but it's still an empty dexapi.go file.

yml is
```yml
--- 
GENERATOR: 
  PackageName: dexapi
  PackageDescription: "Package dexapi provides Go bindings for Dex Tools 2.23 for IWR3 decode to DF3"
  PackageLicense: "THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS."
  Includes: ["DexApi.h"]
    
PARSER: 
  SourcesPaths: ["DexApi.h"]

  Rules: 
    global:
      - {action: accept, from: "^set_work_dir$"}
      - {action: accept, from: "^make_strips$"}
      - {action: accept, from: "^list_forward$"}
      - {action: accept, from: "^list_phy_toc$"}
```

result dexapi.go is:
```go
package dexapi

/*
#include "DexApi.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
```
