### ISSUE TITLE
nidaqmx part 2

### ISSUE THREAD

**Issue by 5k3105** [xlab/c-for-go#22]
(Btw, I've sent you an email)
It was working for a few months but I changed my env settings, including removing:

```CGO_CFLAGS=-D__linux__=1```
```CGO_LDFLAGS=-L/c/goworksp/src/local/nidaqmx –lnicaiu```
Rebuilding the bindings and putting the env vars back like before I now get:

```
C:\goworksp\src\local\telem
λ go build
# local/nidaqmx
..\nidaqmx\nidaqmx.go:20: cannot use cTaskHandle (type *unsafe.Pointer) as type *C.TaskHandle in argument to func literal
..\nidaqmx\nidaqmx.go:29: cannot use cTaskHandle (type *unsafe.Pointer) as type *C.TaskHandle in argument to func literal
..\nidaqmx\nidaqmx.go:38: cannot use cTaskHandle (type unsafe.Pointer) as type C.TaskHandle in argument to func literal
..\nidaqmx\nidaqmx.go:46: cannot use cTaskHandle (type unsafe.Pointer) as type C.TaskHandle in argument to func literal
..\nidaqmx\nidaqmx.go:54: cannot use cTaskHandle (type unsafe.Pointer) as type C.TaskHandle in argument to func literal
..\nidaqmx\nidaqmx.go:62: cannot use cTaskHandle (type unsafe.Pointer) as type C.TaskHandle in argument to func literal
..\nidaqmx\nidaqmx.go:71: cannot use cTaskHandle (type unsafe.Pointer) as type C.TaskHandle in argument to func literal
..\nidaqmx\nidaqmx.go:80: cannot use cTaskHandle (type unsafe.Pointer) as type C.TaskHandle in argument to func literal
..\nidaqmx\nidaqmx.go:89: cannot use cTaskHandle (type unsafe.Pointer) as type C.TaskHandle in argument to func literal
..\nidaqmx\nidaqmx.go:102: cannot use cTask (type unsafe.Pointer) as type C.TaskHandle in argument to func literal
..\nidaqmx\nidaqmx.go:102: too many errors
```
But I never understood why ` CGO_CFLAGS=-D__linux__=1`. I am on a windows machine and the driver is a dll. But it was working at one time.
```
--------------------------------------------------
--- 
GENERATOR: 
  PackageName: nidaqmx
  PackageDescription: "Package nidaqmx provides Go bindings for National Instruments NIDAQmx"
  PackageLicense: "THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS."
  Includes: ["NIDAQmx.h"]
  
PARSER: 
  SourcesPaths: ["NIDAQmx.h"]
  Defines:
    __linux__: 1
  
TRANSLATOR: 
  ConstRules: 
    defines: expand
    
  PtrTips:
    function:
      - {target: ^DAQmxCreateTask$, tips: [0,ref]}
      - {target: ^DAQmxReadAnalogF64$, tips: [0, 0, 0, 0, 0, 0, ref, ref]}
  Rules: 
    global:   
      - {action: ignore, from: "^DAQmxCreate[^T|^A]+"}   
      - {action: ignore, from: "^DAQmxGet"}
      - {action: ignore, from: "^DAQmxSet"}
      - {action: accept, from: "^DAQmx"}
      - {action: replace, from: "^DAQmx"}
      - {transform: export}
    post-global: 
      - {action: replace, from: _$}
      - {load: snakecase}

--------------------------------------------------
```

first part of generated nidaqmx.go:
```go
// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 28 Mar 2017 13:13:51 MDT.
// By https://git.io/c-for-go. DO NOT EDIT.

package nidaqmx

/*
#include "NIDAQmx.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// LoadTask function as declared in nidaqmx\NIDAQmx.h:2509
func LoadTask(TaskName string, TaskHandle []unsafe.Pointer) int32 {
	cTaskName, _ := unpackPCharString(TaskName)
	cTaskHandle, _ := (*unsafe.Pointer)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&TaskHandle)).Data)), cgoAllocsUnknown
	__ret := C.DAQmxLoadTask(cTaskName, cTaskHandle)
	__v := (int32)(__ret)
	return __v
}

// CreateTask function as declared in nidaqmx\NIDAQmx.h:2510
func CreateTask(TaskName string, TaskHandle unsafe.Pointer) int32 {
	cTaskName, _ := unpackPCharString(TaskName)
	cTaskHandle, _ := (*unsafe.Pointer)(unsafe.Pointer(TaskHandle)), cgoAllocsUnknown
	__ret := C.DAQmxCreateTask(cTaskName, cTaskHandle)
	__v := (int32)(__ret)
	return __v
}

// AddGlobalChansToTask function as declared in nidaqmx\NIDAQmx.h:2512
func AddGlobalChansToTask(TaskHandle unsafe.Pointer, ChannelNames string) int32 {
	cTaskHandle, _ := (unsafe.Pointer)(TaskHandle), cgoAllocsUnknown
	cChannelNames, _ := unpackPCharString(ChannelNames)
	__ret := C.DAQmxAddGlobalChansToTask(cTaskHandle, cChannelNames)
	__v := (int32)(__ret)
	return __v
}

// StartTask function as declared in nidaqmx\NIDAQmx.h:2514
func StartTask(TaskHandle unsafe.Pointer) int32 {
	cTaskHandle, _ := (unsafe.Pointer)(TaskHandle), cgoAllocsUnknown
	__ret := C.DAQmxStartTask(cTaskHandle)
	__v := (int32)(__ret)
	return __v
}

// StopTask function as declared in nidaqmx\NIDAQmx.h:2515
func StopTask(TaskHandle unsafe.Pointer) int32 {
	cTaskHandle, _ := (unsafe.Pointer)(TaskHandle), cgoAllocsUnknown
	__ret := C.DAQmxStopTask(cTaskHandle)
	__v := (int32)(__ret)
	return __v
}

// ClearTask function as declared in nidaqmx\NIDAQmx.h:2517
func ClearTask(TaskHandle unsafe.Pointer) int32 {
	cTaskHandle, _ := (unsafe.Pointer)(TaskHandle), cgoAllocsUnknown
	__ret := C.DAQmxClearTask(cTaskHandle)
	__v := (int32)(__ret)
	return __v
}
```
