### ISSUE TITLE
Bitfield assignment is broken

### ISSUE THREAD

**Issue by pwaller** [xlab/c-for-go#26]
# bitfield.yml

```yml
---
GENERATOR:
  PackageName: bitfield
  PackageDescription: "n.a."
  PackageLicense: "n.a."
  Includes: [bitfield.h]
  FlagGroups:
  # Because I am lazy and trying to get this working quickly.
  - {name: "LDFLAGS", flags: ["-Wl,--allow-multiple-definition"]}

PARSER:
  IncludePaths: [.]
  SourcesPaths: [bitfield/bitfield.h]

TRANSLATOR:
  Rules:
    global:
      - {action: accept}
      - {action: ignore, from: "__GO__"}
```

# bitfield/bitfield.h

```
#pragma once

typedef struct {
        int x : 8;
        int y : 8;
        int z : 16;
        unsigned int zz : 16;
        signed int a : 32;
        long int b : 64;
} Foo;

void dofoo(Foo *foo) {}

```

# Go compiler output:

```
c-for-go bitfield.yml && go build -v ./bitfield
```

```
bitfield/cgo_helpers.go:123: cannot use C.int(x.x) (type C.int) as type uint8 in assignment
bitfield/cgo_helpers.go:127: cannot use C.int(x.y) (type C.int) as type uint8 in assignment
bitfield/cgo_helpers.go:131: cannot use C.int(x.z) (type C.int) as type uint16 in assignment
bitfield/cgo_helpers.go:135: cannot use C.uint(x.zz) (type C.uint) as type uint16 in assignment
bitfield/cgo_helpers.go:139: cannot use C.int(x.a) (type C.int) as type uint32 in assignment
bitfield/cgo_helpers.go:143: cannot use C.long(x.b) (type C.long) as type uint64 in assignment
```

# Comment

Sorry, I ran out of time to describe things in detail. Hopefully the problem is clear from the above. It seems like a quirk of the Go compiler that it expects different types than used in the type definition in this circumstance.

I have a work in progress patch which seems to fix the problem:

https://github.com/pwaller/cgogen/commit/6c435cecf788aba6513db2ebf766680689259477

If it's a valid approach, I would like to submit it as a PR, once it's tidied up.
