### ISSUE TITLE
cannot determine size of struct

### ISSUE THREAD

**Issue by tejasmanohar** [xlab/c-for-go#36]
```
GENERATOR:
  PackageName: libproc
  PackageDescription: "Package vorbis provides Go bindings for OggVorbis implementation by the Xiph.Org Foundation"
  PackageLicense: "THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS."
  Includes: ["libproc.h"]
  Options:
    SafeStrings: true
PARSER:
  IncludePaths: ["/usr/include", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/"]
  SourcesPaths: ["/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdks/MacOSX.sdk/usr/include/libproc.h"]
TRANSLATOR:
    MemTips:
      - {target: ^proc_$, self: raw}
```

I tried to run this on some OS X internal libraries (notably libproc.h). I'm guessing there's some dynamic info in type declarations (e.g. sizeof). Any ideas on where to start debugging or if there's a known limitation 
before I dig in?

**Comment by xlab** [comment]
Hi, thanks for the report, the error you're getting looks like this:

```
$ c-for-go libproc.yaml
  processing libproc.yaml ⠦[ERR] /usr/include/net/if.h:163:17: cannot determine size of struct if_data (and 5 more errors)
```

It's a result of CC was unable to understand header file, as some defines are not there. In this case it's required to run c-for-go with defines copied from GCC environment:

```
$ c-for-go -ccdefs libproc.yaml
```

I'm currently investigating what's the problem now with these defs

```
  processing libproc.yaml ⠦[ERR] /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/_types/_fd_def.h:54:1: unexpected '{', expected one of [',', ';', '=']
```

From this code:

```c
#ifdef FD_SETSIZE
#define	__DARWIN_FD_SETSIZE	FD_SETSIZE
#else /* !FD_SETSIZE */
#define	__DARWIN_FD_SETSIZE	1024
#endif /* FD_SETSIZE */
#define	__DARWIN_NBBY		8				/* bits in a byte */
#define __DARWIN_NFDBITS	(sizeof(__int32_t) * __DARWIN_NBBY) /* bits per mask */
#define	__DARWIN_howmany(x, y)	((((x) % (y)) == 0) ? ((x) / (y)) : (((x) / (y)) + 1)) /* # y's == x bits? */

__BEGIN_DECLS
typedef	struct fd_set {
	__int32_t	fds_bits[__DARWIN_howmany(__DARWIN_FD_SETSIZE, __DARWIN_NFDBITS)];
} fd_set;
__END_DECLS

/* This inline avoids argument side-effect issues with FD_ISSET() */
static __inline int
__darwin_fd_isset(int _n, const struct fd_set *_p)
{
	return (_p->fds_bits[(unsigned long)_n/__DARWIN_NFDBITS] & ((__int32_t)(((unsigned long)1)<<((unsigned long)_n % __DARWIN_NFDBITS))));
}
```

**Comment by xlab** [comment]
1) Please update c-for-go by running `go get -u github.com/xlab/c-for-go`, I added a non-related fix

2) If you wish to proceed, you can remove the function at `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/_types/_fd_def.h:54`  it will generate with no problems after that. I'll study the problem with that function, probably sizeof not being properly processed by CC

**Comment by xlab** [comment]
>   IncludePaths: ["/usr/include", 

This is also redundant

**Comment by tejasmanohar** [comment]
```
/* This inline avoids argument side-effect issues with FD_ISSET() */
/* static __inline int
__darwin_fd_isset(int _n, const struct fd_set *_p)
{
	return (_p->fds_bits[(unsigned long)_n/__DARWIN_NFDBITS] & ((__int32_t)(((unsigned long)1)<<((unsigned long)_n % __DARWIN_NFDBITS))));
}*/
```
seems to not generate after changing that file to look like this ^ ? 

Tejas-Macbook:_reference tejas$ c-for-go libproc.yaml
  processing libproc.yaml ⠼[ERR] /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/net/if.h:163:17: cannot determine size of struct if_data (and 7 more errors)

**Comment by tejasmanohar** [comment]
if.h on my computer https://gist.github.com/tejasmanohar/9511878258b4ec21440316592ef7cfd2

**Comment by xlab** [comment]
I addressed this exact issue in previous comment:

**it's required to run c-for-go with defines copied from GCC environment:**
```
$ c-for-go -ccdefs libproc.yaml
```

note the `-ccdefs` flag, please try with it

**Comment by tejasmanohar** [comment]
Oops, sorry. I only saw your 2nd, 3rd comment. Not your first.

I tried with that flag and got 
```
  processing libproc.yaml ⠴[ERR] /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/sys/_types/_fd_def.h:54:1: unexpected '{', expected one of [',', ';', '=']
```
(another fd_def.h) -> so I changed that fd_def.h the same way but I got

```
  processing libproc.yaml ⠼[ERR] /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/sys/mount.h:400:29: unexpected identifier __attribute, expected one of ['(', ')', ',', ':', ';', '=', '[', '{', _Bool, _Complex, _Noreturn, _Static_assert, asm, auto, char, const, double, enum, extern, float, inline, int, long, register, restrict, short, signed, static, struct, typedef, typedefname, typeof, union, unsigned, void, volatile]
```

Maybe CC doesn't support __attribute function syntax?

**Comment by xlab** [comment]
I'm still using this config:

```yaml
GENERATOR:
  PackageName: libproc
  PackageDescription: "Package vorbis provides Go bindings for OggVorbis implementation by the Xiph.Org Foundation"
  PackageLicense: "THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS."
  Includes: ["libproc.h"]
  Options:
    SafeStrings: true
PARSER:
  IncludePaths: ["/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/"]
  SourcesPaths: ["/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdks/MacOSX.sdk/usr/include/libproc.h"]
  
  Defines:


TRANSLATOR:
    MemTips:
      - {target: ^proc_$, self: raw}
    Rules: 
      global: 
        - {transform: lower}
        - {action: accept, from: "^proc_"}
        - {action: replace, from: "^proc_", to: _}
        - {transform: export}
      const:
        - {action: accept, from: "^PROC_"}
        - {action: replace, from: "^PROC_", to: _}
      type: 
        - {action: replace, from: "_t$"}
      private:
        - {transform: unexport}
      post-global:
        - {action: replace, from: _$}
        - {load: snakecase}
```

And getting nothing about `Frameworks/Kernel.framework`. Have you added some additional paths?

Btw, added support for `__attribute`, please update `go get -u github.com/xlab/c-for-go`
