### ISSUE TITLE
unexpected identifier size_t, expected optional parameter type list or one of....

### ISSUE THREAD

**Issue by klokare** [xlab/c-for-go#37]
Looking to generate binding for [MPFR](http://www.mpfr.org). It's header, mpfr.h, depends on the gmp.h header associated with GMP. When I execute (i added the -ccdefs mentioned in earlier issue)

```bash
c-for-go -ccdefs mpfr.yaml
```
I get this error

> processing mpfr.yaml ⠙[ERR] /usr/include/x86_64-linux-gnu/gmp.h:482:57: unexpected identifier size_t, expected optional parameter type list or one of [')', _Bool, _Complex, _Noreturn, auto, char, const, double, enum, extern, float, inline, int, long, register, restrict, short, signed, static, struct, typedef, typedefname, typeof, union, unsigned, void, volatile]

Here is my .yaml

```yaml
GENERATOR: 
  PackageName: mpfr
  PackageDescription: "Package mpfr provides Go bindings for the GNU MPFR library"
  PackageLicense: "THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS."
  SysIncludes: ["mpfr.h"]
  Options:
    SafeStrings: true

PARSER: 
  IncludePaths: ["/usr/include", "/usr/include/x86_64-linux-gnu", "/usr/include/linux"]
  SourcesPaths: ["mpfr.h"]

TRANSLATOR: 
  ConstRules: 
    defines: eval
  PtrTips:
    function:
      - {target: "mpfr_synthesis_pcmout$", tips: [ref,arr]}
      - {target: ^mpfr_, tips: [ref,ref,ref]}
  Rules: 
    global: 
      - {transform: lower}
      - {action: accept, from: "^mpfr_"}
      - {action: replace, from: "^mpfr_", to: _}
      - {transform: export}
    const:
      - {action: accept, from: "^MPFR_"}
      - {action: replace, from: "^mpfr_", to: _}
    type: 
      - {action: replace, from: "_t$"}
    private:
      - {transform: unexport}
    post-global: 
      - {action: doc, from: "^mpfr_", to: "https://xiph.org/mpfr/doc/libmpfr/$name.html"}
      - {action: replace, from: _$}
      - {load: snakecase}
```

Still have a bit of cleanup with the license and docs but wanted to get it working before finalising the .yaml.
