### ISSUE TITLE
Invalid type specifier typedef struct

### ISSUE THREAD

**Issue by sithembiso** [xlab/c-for-go#39]
I should probably prefix this by mentioning that I haven't done any C/C++ development in 5 years. I probably have much bigger issues here than this error, but any input will be appreciated.

The parser is complaining about this definition:
```c
typedef struct {
    C4ErrorDomain domain;
    int32_t code;
    int32_t internal_info;
} C4Error;
```
Config file (trying to start small):
```yaml
--- 
GENERATOR: 
  PackageName: golite
  PackageDescription: "coming soon"
  PackageLicense: "THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS."
  FlagGroups:
    - {name: LDFLAGS, flags: [""]}
  Includes:
    - include/c4.h
  SysIncludes:
    - /usr/local/lib

PARSER:
  Defines:
    __STDC_HOSTED__: null

  IncludePaths:
    - ./include
    - /System/Library/Frameworks/Kernel.framework/Versions/A/Headers

  SourcesPaths:
    - include/c4.h

TRANSLATOR: 
  ConstRules: 
    defines: expand
    enum: expand
```

When I run:
```
c-for-go -out .. go-lite.yml 
```

I get errors:
```
⠋include/c4Base.h:184:9: invalid type specifier
include/c4Base.h:207:13: invalid type specifier
include/c4Base.h:294:28: redeclaration of C4LogDomain 'typedef struct c4LogDomain*' with no linkage, previous declaration at include/c4Base.h:294:28 'typedef struct c4LogDomain*'
include/c4Base.h:297:14: redeclaration of C4LogCallback 'typedef void(*)(struct c4LogDomain*,char,const char*,void*)' with no linkage, previous declaration at include/c4Base.h:297:14 'typedef void(*)(struct c4LogDomain*,char,const char*,void*)'
include/c4BlobStore.h:11:10: include file not found: stdio.h
include/c4Base.h:184:9: invalid type specifier
include/c4Base.h:207:13: invalid type specifier
include/c4Base.h:294:28: redeclaration of C4LogDomain 'typedef struct c4LogDomain*' with no linkage, previous declaration at include/c4Base.h:294:28 'typedef struct c4LogDomain*'
include/c4Base.h:297:14: redeclaration of C4LogCallback 'typedef void(*)(struct c4LogDomain*,char,const char*,void*)' with no linkage, previous declaration at include/c4Base.h:297:14 'typedef void(*)(struct c4LogDomain*,char,const char*,void*)'
include/c4Database.h:53:13: invalid type specifier
too many errors
```

**Comment by xlab** [comment]
Hi, I tried this myself and have no problems with generating the Go bindings for that header file:
https://github.com/couchbase/couchbase-lite-core/blob/master/C/include/c4Base.h

See the results: [Archive.zip](https://github.com/xlab/c-for-go/files/1280647/Archive.zip)

I moved on and included the types, functions and constants too with:
```yaml
  Rules: 
    global: 
      - {action: accept, from: "^c4"}
      - {action: replace, from: "^c4", to: _}
      - {action: accept, from: "^kC4"}
      - {action: replace, from: "^kC4", to: _}
      - {transform: export}
    type: 
      - {action: replace, from: "_t$"}
    private:
      - {transform: unexport}
    post-global: 
      - {action: replace, from: _$}
      - {load: snakecase}
```

**Comment by sithembiso** [comment]
Interesting, it seems like the issue only appears when I have more than one header files (if I include `c4.h` for instance, which includes other header files). The output of the config below looks like this:
```
include/c4Base.h:184:9: invalid type specifier
include/c4Base.h:207:13: invalid type specifier
include/c4Base.h:294:28: redeclaration of C4LogDomain 'typedef struct c4LogDomain*' with no linkage, previous declaration at include/c4Base.h:294:28 'typedef struct c4LogDomain*'
include/c4Base.h:297:14: redeclaration of C4LogCallback 'typedef void(*)(struct c4LogDomain*,char,const char*,void*)' with no linkage, previous declaration at include/c4Base.h:297:14 'typedef void(*)(struct c4LogDomain*,char,const char*,void*)'
include/c4BlobStore.h:11:10: include file not found: stdio.h
include/c4Base.h:184:9: invalid type specifier
include/c4Base.h:207:13: invalid type specifier
include/c4Base.h:294:28: redeclaration of C4LogDomain 'typedef struct c4LogDomain*' with no linkage, previous declaration at include/c4Base.h:294:28 'typedef struct c4LogDomain*'
include/c4Base.h:297:14: redeclaration of C4LogCallback 'typedef void(*)(struct c4LogDomain*,char,const char*,void*)' with no linkage, previous declaration at include/c4Base.h:297:14 'typedef void(*)(struct c4LogDomain*,char,const char*,void*)'
include/c4Database.h:53:13: invalid type specifier
too many errors
```

Notice the addition of `c4.h` below:
```yaml
--- 
GENERATOR: 
  PackageName: golite
  PackageDescription: "coming soon"
  PackageLicense: "THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS."
  FlagGroups:
    - {name: LDFLAGS, flags: [""]}
  Includes:
    - c4.h
  SysIncludes:
    - /usr/local/lib

PARSER:
  Defines:
    __STDC_HOSTED__: null

  IncludePaths:
    - ./include
    - /System/Library/Frameworks/Kernel.framework/Versions/A/Headers

  SourcesPaths:
    - c4.h

TRANSLATOR:
  ConstRules:
    defines: expand
    enum: expand
  Rules:
    global:
      - {action: accept, from: "^c4"}
      - {action: replace, from: "^c4", to: _}
      - {action: accept, from: "^kC4"}
      - {action: replace, from: "^kC4", to: _}
      - {transform: export}
    type:
      - {action: replace, from: "_t$"}
    private:
      - {transform: unexport}
    post-global:
      - {action: replace, from: _$}
      - {load: snakecase}
```

Is c-for-go perhaps not meant to handle multiple files at a time? I saw similar examples on other projects that use it?

Thanks

**Comment by cznic** [comment]
Blind shot: There's a particular [option](https://github.com/cznic/cc/blob/b98d4a758e7bcca3eabdbc1ae0139db6e52252ab/cc.go#L490) allowing _compatible_ typedef redeclarations. Is it enebaled in c-for-go?

**Comment by xlab** [comment]
@cznic certainly no, I allowed only what was preset at the moment, years ago:

```go
	return cc.Parse(predefined, cfg.SourcesPaths, model,
		cc.SysIncludePaths(cfg.IncludePaths),
		cc.EnableAnonymousStructFields(),
		cc.EnableAsm(),
		cc.EnableAlternateKeywords(),
		cc.EnableIncludeNext(),
		cc.EnableNoreturn(),
		cc.EnableEmptyDeclarations(),
		cc.EnableWideEnumValues(),
		cc.EnableWideBitFieldTypes(),
	)
```

I will try to enable everything.

**Comment by xlab** [comment]
@sithembiso ok, try now, I enabled the extension that may allow that to be parsed.

> Is c-for-go perhaps not meant to handle multiple files at a time?

No, you can have as much files as you want, but some C headers are extremely crappy, it is the first project I saw with this problem.

**Comment by xlab** [comment]
N.B. @cznic enabling all extensions will break stuff, so I will add them only on case-by-case basis.

**Comment by cznic** [comment]
> enabling all extensions will break stuff, so I will add them only on case-by-case basis.

That's reasonable.

**Comment by sithembiso** [comment]
@xlab thanks, it's working now even though its producing a lot of duplicates and some types are undefined. Some functions appear at lease 12 times like this:

```go
// Str function as declared in include/c4Base.h:223
func Str(str string) C4Slice {
	cstr, _ := unpackPCharString(str)
	__ret := C.c4str(cstr)
	__v := *NewC4SliceRef(unsafe.Pointer(&__ret))
	return __v
}

// Str function as declared in include/c4Base.h:223
func Str(str string) C4Slice {
	cstr, _ := unpackPCharString(str)
	__ret := C.c4str(cstr)
	__v := *NewC4SliceRef(unsafe.Pointer(&__ret))
	return __v
}

// Str function as declared in include/c4Base.h:223
func Str(str string) C4Slice {
	cstr, _ := unpackPCharString(str)
	__ret := C.c4str(cstr)
	__v := *NewC4SliceRef(unsafe.Pointer(&__ret))
	return __v
}

// Str function as declared in include/c4Base.h:223
func Str(str string) C4Slice {
	cstr, _ := unpackPCharString(str)
	__ret := C.c4str(cstr)
	__v := *NewC4SliceRef(unsafe.Pointer(&__ret))
	return __v
}

// Str function as declared in include/c4Base.h:223
func Str(str string) C4Slice {
	cstr, _ := unpackPCharString(str)
	__ret := C.c4str(cstr)
	__v := *NewC4SliceRef(unsafe.Pointer(&__ret))
	return __v
}

// Str function as declared in include/c4Base.h:223
func Str(str string) C4Slice {
	cstr, _ := unpackPCharString(str)
	__ret := C.c4str(cstr)
	__v := *NewC4SliceRef(unsafe.Pointer(&__ret))
	return __v
}

// Str function as declared in include/c4Base.h:223
func Str(str string) C4Slice {
	cstr, _ := unpackPCharString(str)
	__ret := C.c4str(cstr)
	__v := *NewC4SliceRef(unsafe.Pointer(&__ret))
	return __v
}

// Str function as declared in include/c4Base.h:223
func Str(str string) C4Slice {
	cstr, _ := unpackPCharString(str)
	__ret := C.c4str(cstr)
	__v := *NewC4SliceRef(unsafe.Pointer(&__ret))
	return __v
}

// Str function as declared in include/c4Base.h:223
func Str(str string) C4Slice {
	cstr, _ := unpackPCharString(str)
	__ret := C.c4str(cstr)
	__v := *NewC4SliceRef(unsafe.Pointer(&__ret))
	return __v
}

// Str function as declared in include/c4Base.h:223
func Str(str string) C4Slice {
	cstr, _ := unpackPCharString(str)
	__ret := C.c4str(cstr)
	__v := *NewC4SliceRef(unsafe.Pointer(&__ret))
	return __v
}

// Str function as declared in include/c4Base.h:223
func Str(str string) C4Slice {
	cstr, _ := unpackPCharString(str)
	__ret := C.c4str(cstr)
	__v := *NewC4SliceRef(unsafe.Pointer(&__ret))
	return __v
}

// Str function as declared in include/c4Base.h:223
func Str(str string) C4Slice {
	cstr, _ := unpackPCharString(str)
	__ret := C.c4str(cstr)
	__v := *NewC4SliceRef(unsafe.Pointer(&__ret))
	return __v
}
```

Here is the final copy of the config file:
```yaml
--- 
GENERATOR: 
  PackageName: golite
  PackageDescription: "coming soon"
  PackageLicense: "THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS."
  FlagGroups:
    - {name: LDFLAGS, flags: [""]}
  Includes:
    - c4Base.h
    - c4BlobStore.h
    - c4Database.h
    - c4Document.h
    - c4DocEnumerator.h
    - c4ExpiryEnumerator.h
    - c4Query.h
    - c4Observer.h
    - c4Replicator.h
  SysIncludes:
    - /usr/local/lib
    - /usr/include

PARSER:
  Defines:
    __STDC_HOSTED__: null

  IncludePaths:
    - ./include
    - ../vendor/fleece/Fleece
    - /System/Library/Frameworks/Kernel.framework/Versions/A/Headers
    - /usr/include

  SourcesPaths:
    - c4Base.h
    - c4BlobStore.h
    - c4Database.h
    - c4Document.h
    - c4DocEnumerator.h
    - c4ExpiryEnumerator.h
    - c4Query.h
    - c4Observer.h
    - c4Replicator.h

TRANSLATOR:
  ConstRules:
    defines: expand
    enum: expand
  Rules:
    global:
      - {action: accept, from: "^c4"}
      - {action: replace, from: "^c4", to: _}
      - {action: accept, from: "^kC4"}
      - {action: replace, from: "^kC4", to: _}
      - {transform: export}
    type:
      - {action: replace, from: "_t$"}
    private:
      - {transform: unexport}
    post-global:
      - {action: replace, from: _$}
      - {load: snakecase}
```

Is there anything wrong I'm doing?
