### ISSUE TITLE
duplicate variable name with certain defines

### ISSUE THREAD

**Issue by jsimonetti** [xlab/c-for-go#40]
Trying to extract the constants from rt.netlink.h (https://raw.githubusercontent.com/torvalds/linux/master/include/uapi/linux/rtnetlink.h) will create duplicate variable names in const.go:

```
    // Base as defined in rtnetlinkh/rtnetlink.h:26
    Base = Base
    // Base as declared in rtnetlinkh/rtnetlink.h:25
    Base = 16
```

The corresponding lines read:
```
enum {
    RTM_BASE    = 16,
#define RTM_BASE    RTM_BASE
```

I used the following config:
```
---
GENERATOR:
  PackageName: rtnetlinkh

PARSER:
  IncludePaths: [/usr/include]
  SourcesPaths: [rtnetlink.h]

TRANSLATOR:
  ConstRules:
    enum: eval
  Rules:
    const:
      - {transform: lower}
      - {action: accept, from: "(?i)rtm_"}
      - {action: replace, from: "(?i)rtm_", to: _}
      - {transform: export}
    post-global:
      - {load: snakecase}
```
