### ISSUE TITLE
/usr/include/bits/byteswap.h:47:10: called object is not a function or function pointer (have '<undefined>')

### ISSUE THREAD

**Issue by XVilka** [xlab/c-for-go#43]
Trying to compile using this config:
```yaml
---
GENERATOR:
    PackageName: radare2
    PackageDescription: "Package radare2 provides Go bindings for radare2 reverse engineering library"
    PackageLicense: "LGPLv3"
    PkgConfigOpts: [libr]
    Includes: ['/usr/local/include/libr/r_core.h', '/usr/local/include/libr/r_asm.h', '/usr/local/include/libr/r_anal.h', '/usr/local/include/libr/r_bin.h', '/usr/local/include/libr/r_debug.h', '/usr/local/include/libr/r_io.h', '/usr/local/include/libr/r_config.h', '/usr/local/include/libr/r_flag.h', '/usr/local/include/libr/r_sign.h', '/usr/local/include/libr/r_hash.h', '/usr/local/include/libr/r_diff.h', '/usr/local/include/libr/r_egg.h', '/usr/local/include/libr/r_fs.h', '/usr/local/include/libr/r_lang.h', '/usr/local/include/libr/r_pdb.h']

PARSER:
    IncludePaths: ["/usr/include","/usr/include/linux", "/usr/local/include", "/usr/local/include/libr"]
    SourcesPaths: ['/usr/local/include/libr/r_core.h', '/usr/local/include/libr/r_asm.h', '/usr/local/include/libr/r_anal.h', '/usr/local/include/libr/r_bin.h', '/usr/local/include/libr/r_debug.h', '/usr/local/include/libr/r_io.h', '/usr/local/include/libr/r_config.h', '/usr/local/include/libr/r_flag.h', '/usr/local/include/libr/r_sign.h', '/usr/local/include/libr/r_hash.h', '/usr/local/include/libr/r_diff.h', '/usr/local/include/libr/r_egg.h', '/usr/local/include/libr/r_fs.h', '/usr/local/include/libr/r_lang.h', '/usr/local/include/libr/r_pdb.h']

TRANSLATOR:
    ConstRules:
        defines: eval
    Rules:
        global:
            - {action: accept, from "^r_"}
            - {transform: export}
        private:
            - {transform: unexport}
```
And using cmdline `c-for-go -ccdefs -ccincl radare2.yml` but seeing this error:
```
 processing radare2.yml ⠸[ERR] /usr/include/bits/byteswap.h:47:10: called object is not a function or function pointer (have '<undefined>') (and 3 more errors)
```
Here are the lines of `usr/include/bits/byteswap.h`:
```c
#ifdef __GNUC__
# if __GNUC_PREREQ (4, 3)
static __inline unsigned int
__bswap_32 (unsigned int __bsx)
{
  return __builtin_bswap32 (__bsx);
}
```
Particularily it doesnt like `__builtin_bswap32 (__bsx)` call
