### ISSUE TITLE
Undefine function when struct has callback as member

### ISSUE THREAD

**Issue by bearx3f** [xlab/c-for-go#60]
When define struct in c and it has callback as member *c-for-go* generate file `cgo_helper.go` that no definition of `PassRef` and `NewRef` for callback

Reproduce:

**header file**
gh.h
```c
#ifndef GH_H
#define GH_H

typedef struct _gh_
{
   void *p;
   int (*callback)(void *ptr);
} GH;

#endif
```

**manifest**

gh.yml
```yml
---
GENERATOR:
  PackageName: gh
  PackageDescription: "Reproduce bug for c-for-go"
  PackageLicense: "THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS."
  Includes: [ gh.h ]

PARSER:
  IncludePaths: 
    - /usr/include
  SourcesPaths: [ gh/gh.h ]

TRANSLATOR: 
  ConstRules: 
    defines: expand
    enum: expand
  Rules: 
    global: 
      - {action: accept, from: "^GH"}

```

types.go
```go
// GH as declared in gh/gh.h:5
type GH struct {
	p              unsafe.Pointer
	callback       *func(ptr unsafe.Pointer) int32
	ref86e6029f    *C.GH
	allocs86e6029f interface{}
}
```

cgo_helper.go
```go
func (x *GH) PassRef() (*C.GH, *cgoAllocMap) {
...
	var ccallback_allocs *cgoAllocMap
	ref86e6029f.callback, ccallback_allocs = x.callback.PassRef() // <-- here PassRef is undefined
	allocs86e6029f.Borrow(ccallback_allocs)
...
}
func (x *GH) Deref() {
	if x.ref86e6029f == nil {
		return
	}
	x.p = (unsafe.Pointer)(unsafe.Pointer(x.ref86e6029f.p))
	x.callback = NewRef(unsafe.Pointer(x.ref86e6029f.callback)) // <-- here NewRef is undefined
}
```

and then build

```
gh/cgo_helpers.go:127:53: x.callback.PassRef undefined (type *func(unsafe.Pointer) int32 has no field or method PassRef)
gh/cgo_helpers.go:152:15: undefined: NewRef
```
