### ISSUE TITLE
processing gcrypt.yml ⠙panic: Enum

### ISSUE THREAD

**Issue by dimaxgl** [xlab/c-for-go#66]
Hi! I'm trying to process libgcrypt bindings with following command:
```bash
c-for-go --ccincl gcrypt.yml
```
Gcrypt.yml file contents:
```yaml
GENERATOR:
  PackageName: vorbis
  PackageDescription: "Package gcrypt"
  PackageLicense: "THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS."
  Includes: ["gcrypt.h"]

PARSER:
  IncludePaths: ["/usr/include","/usr/include/x86_64-linux-gnu"]
  SourcesPaths: ["gcrypt.h"]

TRANSLATOR:
  ConstRules:
    defines: expand
    enum: expand
```

And we get next result:
```bash
  processing gcrypt.yml ⠙panic: Enum

goroutine 1 [running]:
github.com/cznic/cc.(*Model).typ(0xb83080, 0x18, 0x9, 0xc0000a2248)
	/home/dm/go/src/github.com/cznic/cc/model.go:204 +0x383
github.com/cznic/cc.(*Model).BinOpType(0xb83080, 0x8de7a0, 0xc00081dd50, 0x8de7a0, 0xc00043b030, 0xc00043b030, 0xc0000103c0)
	/home/dm/go/src/github.com/cznic/cc/model.go:1541 +0x38e
github.com/cznic/cc.(*Model).binOp(0xb83080, 0xc000294e00, 0x8d1360, 0xc00081b500, 0x8d1360, 0xc00081b5c0, 0xc0000a2358, 0xf5784063, 0x932aa9644b4a2b40, 0xc0000a2388, ...)
	/home/dm/go/src/github.com/cznic/cc/model.go:1451 +0x2b7
github.com/cznic/cc.(*Expression).eval(0xc00081b680, 0xc000294e00, 0x20, 0x8de7a0, 0xc00081b2d8, 0x8de7a0)
	/home/dm/go/src/github.com/cznic/cc/ast2.go:2402 +0xb207
github.com/cznic/cc.(*Expression).cond(0xc00085e6c0, 0xc000294e00, 0x8d13a0, 0xc000719720)
	/home/dm/go/src/github.com/cznic/cc/ast2.go:749 +0x60
github.com/cznic/cc.(*Expression).eval(0xc00085e6c0, 0xc000294e00, 0xc0000a31d0, 0x40bd78, 0x8, 0x7d3f20)
	/home/dm/go/src/github.com/cznic/cc/ast2.go:2541 +0x12bd
github.com/cznic/cc.(*ExpressionList).eval(0xc000719950, 0xc000294e00, 0x4d, 0xc0001d3318, 0x8de700, 0xc000294e00)
	/home/dm/go/src/github.com/cznic/cc/ast2.go:2716 +0x75
github.com/cznic/cc.yyParse(0x8d13e0, 0xc000294e00, 0x0)
	/home/dm/go/src/github.com/cznic/cc/parser.go:3301 +0x3ef0
github.com/cznic/cc.Parse(0xc0001b4380, 0x310, 0xc00005c950, 0x1, 0x1, 0xb83080, 0xc0000a7c88, 0xa, 0xa, 0x0, ...)
	/home/dm/go/src/github.com/cznic/cc/cc.go:830 +0x5e9
github.com/xlab/c-for-go/parser.ParseWith(0xc0001f0200, 0xc00000cee0, 0x2, 0x2)
	/home/dm/go/src/github.com/xlab/c-for-go/parser/parser.go:101 +0x10fb
main.NewProcess(0x7ffc940f12fe, 0xa, 0x0, 0x0, 0xc00001a810, 0xc00023cd80, 0x40bd78)
	/home/dm/go/src/github.com/xlab/c-for-go/process.go:80 +0x2b5
main.main()
	/home/dm/go/src/github.com/xlab/c-for-go/main.go:79 +0x1c0
```

Where problem can be?
