### ISSUE TITLE
[Help] Sundials

### ISSUE THREAD

**Issue by mantielero** [xlab/c-for-go#67]
Hello I am trying to create some bindings with [Sundials](https://github.com/LLNL/sundials). I have little clue about C/C++ and I have just started with Go a couple of weeks ago. 

After this disclaimer, I am trying to start little by little with the bindings. What I have now is:
```yaml
---
GENERATOR:
  PackageName: test
  PackageDescription: "Sundial's nvector-serial"
  PackageLicense: "THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS."
  #PkgConfigOpts: []
  Includes:
    #- "../sundials-master/build/include/sundials/sundials_config.h"
    - "../sundials-master/include/sundials/sundials_types.h" # This gets included in cgo_helpers.go
    - "../sundials-master/include/sundials/sundials_math.h"
  Options:
    SafeStrings: true

PARSER:
  IncludePaths: ["sundials-master/build/include/", "sundials-master/include/", "/usr/include",  "/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/include/"]
  #SourcesPaths: [ "./sundials-master/include/nvector/nvector_serial.h"]
  SourcesPaths:
    #- "./sundials-master/build/include/sundials/sundials_config.h"
    - "./sundials-master/include/sundials/sundials_types.h"
    - "./sundials-master/include/sundials/sundials_math.h"

TRANSLATOR:
  ConstRules:
    defines: eval
    enums: eval
  Defines:
    SUNDIALS_MPI_COMM_F2C: 1
    SUNDIALS_DOUBLE_PRECISION: yes
  #TypeTips:
  #  function:
  #    - {target: "^opus_", self: plain, tips: [plain,plain,plain,plain,plain]}
  #PtrTips:
  #  function:
  #    - {target: "^fmi2_set_debug_logging", tips: [0,0,size,arr] }
      #- {target: "_encoder_create$", tips: [0,0,0,ref]}
      #- {target: "_decoder_create$", tips: [0,0,ref]}
      #- {target: "_multistream_packet_unpad$", tips: [0,size,0]}
      #- {target: "_multistream_packet_pad$", tips: [0,size,size,0]}
      #- {target: "_packet_unpad$", tips: [0,size]}
      #- {target: "_packet_pad$", tips: [0,size,size]}
      #- {target: "_pcm_soft_clip$", tips: [arr,0,0,arr]}
      #- {target: ^opus_, tips: [ref]}
  Rules:
    global:
      - {transform: title}
      - {action: accept, from: "^N_V"}
      #- {action: accept, from: "^C"}
      #- {action: accept, from: "^SUNMatrix"}
      - {action: accept, from: "^SUNDIALS"}
      - {action: accept, from: "^SUN"}      
      - {action: accept, from: "^RCONST"}
      - {transform: export}
    #function:
    #  - {action: ignore, from: "fmi2_default_callback_logger"} #variadic
    #  - {action: ignore, from: "fmi2_log_forwarding"}  # variadic
    #  - {action: ignore, from: "jm_log"} # variadic
    #  - {action: ignore, from: "_encoder_ctl"} # variadic
    #  - {action: ignore, from: "_decoder_ctl"} # variadic
    #  - {action: ignore, from: "_packet_parse"} # internal

    const:
      - {action: accept, from: "^SUN"}
      - {action: ignore, from: "^SUNDIALS_MPI_COMM_F2C"}
      - {action: accept, from: "^BIG"}
      - {action: accept, from: "^SMALL"}
      - {action: accept, from: "^UNIT"}
      - {action: accept, from: "^_SUNDIALSMATH"}
      - {transform: export}
    type:
      #- {action: accept, from: "^_N"}
      - {action: accept, from: "^FILE"}
      - {action: accept, from: "^N_V"}
      - {action: accept, from: "^sunindextype"}
      - {action: accept, from: "^realtype"}
      - {action: accept, from: "^booleantype"}
      #- {action: accept, from: "^C"}
      #- {action: accept, from: "^SUNMatrix"}
      #- {action: replace, from: "_t$"}
    private:
      - {transform: unexport}
    post-global:
      - {action: replace, from: _$}
      - {load: snakecase}
```

When I run `go build`, I get:
```
# _/home/jose/src/golang/sundials/test
/usr/bin/ld: $WORK/b001/_x004.o: en la función `_cgo_f88c58d04f65_Cfunc_SUNRpowerI':
/tmp/go-build/cgo-gcc-prolog:53: referencia a `SUNRpowerI' sin definir
/usr/bin/ld: $WORK/b001/_x004.o: en la función `_cgo_f88c58d04f65_Cfunc_SUNRpowerR':
/tmp/go-build/cgo-gcc-prolog:72: referencia a `SUNRpowerR' sin definir
collect2: error: ld devolvió el estado de salida 1
```
meaning something like: reference to 'SUNRpowerI' not defined.

**Comment by xlab** [comment]
Looks like headers are there, but you missed couple of shared libraries from including in LDFLAGS.
So function `SUNRpowerI` is referenced, but not linked.

Put a file that is hand written that will include libs for each platforms correctly. Example:
https://github.com/go-gl/glfw/blob/master/v3.2/glfw/build.go

Official doc on cgo directives:
https://golang.org/cmd/cgo/

**Comment by mantielero** [comment]
I am trying with a different bit of sundials to see if I have better success. I am trying to bind with `libsundials_nvecserial.so`.

I have Sundials installed in Archlinux. The libraries available are:
```
/usr/lib/libsundials_arkode.so
/usr/lib/libsundials_cvode.so
/usr/lib/libsundials_cvodes.so
/usr/lib/libsundials_fnvecopenmp.so
/usr/lib/libsundials_fnvecparallel.so
/usr/lib/libsundials_fnvecserial.so
/usr/lib/libsundials_fsunlinsolband.so
/usr/lib/libsundials_fsunlinsoldense.so
/usr/lib/libsundials_fsunlinsolklu.so
/usr/lib/libsundials_fsunlinsolpcg.so
/usr/lib/libsundials_fsunlinsolspbcgs.so
/usr/lib/libsundials_fsunlinsolspfgmr.so
/usr/lib/libsundials_fsunlinsolspgmr.so
/usr/lib/libsundials_fsunlinsolsptfqmr.so
/usr/lib/libsundials_fsunmatrixband.so
/usr/lib/libsundials_fsunmatrixdense.so
/usr/lib/libsundials_fsunmatrixsparse.so
/usr/lib/libsundials_fsunnonlinsolfixedpoint.so
/usr/lib/libsundials_fsunnonlinsolnewton.so
/usr/lib/libsundials_ida.so
/usr/lib/libsundials_idas.so
/usr/lib/libsundials_kinsol.so
/usr/lib/libsundials_nvecopenmp.so
/usr/lib/libsundials_nvecparallel.so
/usr/lib/libsundials_nvecserial.so
/usr/lib/libsundials_sunlinsolband.so
/usr/lib/libsundials_sunlinsoldense.so
/usr/lib/libsundials_sunlinsolklu.so
/usr/lib/libsundials_sunlinsolpcg.so
/usr/lib/libsundials_sunlinsolspbcgs.so
/usr/lib/libsundials_sunlinsolspfgmr.so
/usr/lib/libsundials_sunlinsolspgmr.so
/usr/lib/libsundials_sunlinsolsptfqmr.so
/usr/lib/libsundials_sunmatrixband.so
/usr/lib/libsundials_sunmatrixdense.so
/usr/lib/libsundials_sunmatrixsparse.so
/usr/lib/libsundials_sunnonlinsolfixedpoint.so
/usr/lib/libsundials_sunnonlinsolnewton.so
```

The file that I am using now is:
```yaml
---
GENERATOR:
  PackageName: nvector
  PackageDescription: "Sundial's nvector-serial"
  PackageLicense: "THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS."
  #PkgConfigOpts:
  #  - sundials
  FlagGroups:
    - {name: "LDFLAGS", flags: ["-lsundials_nvecserial", "-L/usr/lib"]}
  SysIncludes: #["../sundials-master/include/nvector/nvector_serial.h", "../sundials-master/include/sundials/sundials_nvector.h"] # This gets included in cgo_helpers.go
    - stdio.h
    - sundials/sundials_types.h
    - nvector/nvector_serial.h
    - sundials/sundials_math.h
  Options:
    SafeStrings: true

PARSER:
  IncludePaths: ["/usr/include", "/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/include/"]
  SourcesPaths:
    - "/usr/include/sundials/sundials_types.h"
    - "/usr/include/nvector/nvector_serial.h"
    - "/usr/include/sundials/sundials_math.h"
    #- "<sundials/sundials_types.h>"
    #- "<nvector/nvector_serial.h>"
    #- "<sundials/sundials_math.h>"

  #SourcesPaths: [ "./sundials-master/include/nvector/nvector_serial.h", "./sundials-master/include/sundials/sundials_nvector.h"] #"sundials-master/include/nvector/nvector_mpiraja.h", "sundials-master/include/nvector/nvector_openmpdev.h", "sundials-master/include/nvector/nvector_openmp.h",]

TRANSLATOR:
  ConstRules:
    defines: eval
    enums: eval

  #TypeTips:
  #  function:
  #    - {target: "^opus_", self: plain, tips: [plain,plain,plain,plain,plain]}
  #PtrTips:
  #  function:
  #    - {target: "^fmi2_set_debug_logging", tips: [0,0,size,arr] }
      #- {target: "_encoder_create$", tips: [0,0,0,ref]}
      #- {target: "_decoder_create$", tips: [0,0,ref]}
      #- {target: "_multistream_packet_unpad$", tips: [0,size,0]}
      #- {target: "_multistream_packet_pad$", tips: [0,size,size,0]}
      #- {target: "_packet_unpad$", tips: [0,size]}
      #- {target: "_packet_pad$", tips: [0,size,size]}
      #- {target: "_pcm_soft_clip$", tips: [arr,0,0,arr]}
      #- {target: ^opus_, tips: [ref]}
  Rules:
    global:
      #- {transform: title}
      - {action: accept, from: "^N_V"}
      - {action: accept, from: "^SUNDIALS"}
      - {action: accept, from: "^SUN"}
      - {action: accept, from: "^RCONST"}
      - {transform: export}
    #function:
    #  - {action: ignore, from: "fmi2_default_callback_logger"} #variadic
    #  - {action: ignore, from: "fmi2_log_forwarding"}  # variadic
    #  - {action: ignore, from: "jm_log"} # variadic
    #  - {action: ignore, from: "_encoder_ctl"} # variadic
    #  - {action: ignore, from: "_decoder_ctl"} # variadic
    #  - {action: ignore, from: "_packet_parse"} # internal

    const:
      - {action: accept, from: "^SUN"}
      - {action: ignore, from: "^SUNDIALS_MPI_COMM_F2C"}
      - {action: accept, from: "^BIG"}
      - {action: accept, from: "^NV"}
      - {action: accept, from: "^SMALL"}
      - {action: accept, from: "^UNIT"}
      - {action: accept, from: "^_SUNDIALSMATH"}
      - {transform: export}

    type:
      - {action: accept, from: "^_N"}
      - {action: accept, from: "^FILE"}
      - {action: accept, from: "^N_V"}
      - {action: accept, from: "^sunindextype"}
      - {action: accept, from: "^realtype"}
      - {action: accept, from: "^booleantype"}
      #- {action: accept, from: "^C"}
      #- {action: accept, from: "^SUNMatrix"}
      #- {action: replace, from: "_t$"}
    private:
      - {transform: unexport}
    post-global:
      - {action: replace, from: _$}
      - {load: snakecase}
```

When I run `go build`, I have similar failures as before:
```
# _/home/jose/src/golang/sundials/nvector
/usr/bin/ld: $WORK/b001/_x004.o: en la función `_cgo_59e8d818a059_Cfunc_N_VClone':
/tmp/go-build/cgo-gcc-prolog:105: referencia a `N_VClone' sin definir
/usr/bin/ld: $WORK/b001/_x004.o: en la función `_cgo_59e8d818a059_Cfunc_N_VCloneEmpty':
```
(in the function .... reference to N_VClone undefined.

I have :
```yaml
  FlagGroups:
    - {name: "LDFLAGS", flags: ["-lsundials_nvecserial", "-L/usr/lib"]}
```
given that I am aiming to link against `libsundials_nvecserial.so`. 

Is this what you where suggesting? Any other clue?

Regards and thanks for your help.
