### ISSUE TITLE
export types also exports function arguments

### ISSUE THREAD

**Issue by Asalle** [xlab/c-for-go#78]
if I specify this in my roc.yml:
```
    type: 
      - {transform: export}
```
it will export fields in my structs (types), but also, function arguments will be CamelCased (with upper-case first letter) like this:
```
func AddressIp(Address *Address, Buf []byte, Bufsz uint) string {}
```

is there any way to avoid the latter?

**Comment by xlab** [comment]
Hi! You need to try to add

```
    private:
      - {transform: unexport}
```

However if this affects struct fields also, that's clearly a bug. Good catch!

**Comment by Asalle** [comment]
😫😭

Thank you fot quick feedback! I'll try it out as soon as possible

**Comment by Asalle** [comment]
thanks, that works somehow!
my rules:
```
 Rules: 
    global: 
      - {transform: lower}
      - {action: accept, from: "^roc_"}
      - {action: replace, from: "^roc_", to: _}
      - {transform: unexport}
    const:
      - {transform: export}
      - {action: accept, from: "^ROC_"}
      - {action: replace, from: "^ROC_", to: _}
    type: 
      - {transform: export}
      - {action: replace, from: "_t$"}
    function:
      - {transform: unexport}
    private:
      - {transform: unexport}
    post-global: 
      - {action: replace, from: _$}
      - {load: snakecase}
```

[source](https://github.com/roc-project/roc-go/blob/master/roc.yml)
