### ISSUE TITLE
[Help] Coolprop

### ISSUE THREAD

**Issue by mantielero** [xlab/c-for-go#82]
I am trying to wrap [CoolProp](https://github.com/CoolProp/CoolProp). I am a newbie in go, coolprop and c-for-go, so what can go wrong? ;oP

I am trying the following:
```yml
--- 
GENERATOR: 
  PackageName: coolprop
  PackageDescription: "Package nidaqmx provides Go bindings for CoolProp"
  PackageLicense: "THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS."
  Includes: 
    - CoolProp.h

PARSER: 
  IncludePaths:
    - ../../include  
  SourcesPaths:
    - CoolPropLib.h

TRANSLATOR: 
  ConstRules: 
    defines: expand

  Rules: 
    global:   
      - {action:accept, from: "Props1SI"}
```

I am getting the following error:
```
[jose@mountain Golang]$ c-for-go coolprop-go.yml 
  processing coolprop-go.yml ⠋[ERR] ../../include/CoolPropLib.h:142:78: unexpected identifier val, expected one of ['(', ')', ',', ':', ';', '=', '[', '{', _Bool, _Complex, _Noreturn, _Static_assert, asm, auto, char, const, double, enum, extern, float, inline, int, long, register, restrict, short, signed, static, struct, typedef, typedefname, typeof, union, unsigned, void, volatile]
```
so it complains about [line 142](https://github.com/CoolProp/CoolProp/blob/master/include/CoolPropLib.h#L142).

Any idea about what am I doing wrong?
