### ISSUE TITLE
[bug] cannot unexport generated functions

### ISSUE THREAD

**Issue by Asalle** [xlab/c-for-go#83]
Hey, here is go-roc's `Rules` section:
```
  Rules: 
    global: 
      - {transform: lower}
      - {action: accept, from: "^roc_"}
      - {action: replace, from: "^roc_", to: _}
      - {transform: unexport}
    const:
      - {transform: export}
      - {action: accept, from: "^ROC_"}
      - {action: replace, from: "^ROC_", to: _}
    type: 
      - {transform: export}
      - {action: replace, from: "_t$"}
    function:
      - {transform: unexport}
    private:
      - {transform: unexport}
    post-global: 
      - {action: replace, from: _$}
      - {load: snakecase}
```
This is the source code:
```
ROC_API int
roc_address_init(roc_address* address, roc_family family, const char* ip, int port);
```

This is the generated code:
```
// AddressInit function as declared in roc/address.h:86
func AddressInit(address *Address, family Family, ip string, port int32) int32 {
// ...
```

I tried adding `      - {action: accept, from: ".*"}` to `function`, but no luck. 

How do I make all generated functions unexported?
