### ISSUE TITLE
[question] How to unexport one particular type?

### ISSUE THREAD

**Issue by Asalle** [xlab/c-for-go#85]
I have my types exported - that's great, but I would like to unexport this one particular type called "Frame", can I do that?

I tried to match it like this:
```
TRANSLATOR: 
  Rules: 
    global: 
      - {transform: lower}
      - {action: accept, from: "^roc_"}
      - {action: replace, from: "^roc_frame", to: "frame", transform: unexport}
```

to no effect :(
